language: php

before_script:
    composer install

script:
    - vendor/bin/phpunit
    - vendor/bin/phpmd src/,tests/ text phpmd.xml
    - vendor/bin/php-cs-fixer fix src/ --diff
    - vendor/bin/php-cs-fixer fix tests/ --diff
    - vendor/bin/php-cs-fixer fix bin/ --diff

